# Generated by Django 3.2.9 on 2021-11-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, default='Anonymous', max_length=500, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Expires Datetime'),
        ),
    ]
